log:
  level: debug
  disable_sentry: true

mime_types:
  allowed_mime_types:
    - image/png
    - image/jpeg
    - image/jpg
    - application/pdf

aws:
  access_key: "AKIATM5TUKXKWTPPLSHJ"
  secret_key: "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"
  bucket: "distributedlabtestbucket"
  region: "eu-west-1"
  expiration: 1h
  ssldisable: true

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: blob-svc
  service_port: 80

doorman:
  service_url: http://localhost:8054/integrations/doorman
