log:
  level: debug
  disable_sentry: true

#db:
#  url: "postgres://blob:blob@localhost:25432/blob?sslmode=disable"

mime_types:
  banner:
    - image/png
    - image/jpeg
    - image/jpg
  file:
    - application/pdf

aws:
  access_key: "AKIATM5TUKXKWTPPLSHJ"
  secret_key: "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"
  bucket: "distributedlabtestbucket"
  region:  "eu-west-1"
  expiration: 1h
  ssldisable: true

jwt:
  signature_key: "default"

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: blob-svc
  service_port: 80
