log:
  level: debug
  disable_sentry: true

mime_types:
  allowed_mime_types:
    - image/png
    - image/jpeg
    - image/jpg
    - application/pdf

aws:
  #endpoint: "http://localstack:4566"
  access_key: "AKIATM5TUKXKWTPPLSHJ"
  secret_key: "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"
  bucket: "dltestbucketdl"
  region: "eu-west-1"
  expiration: 1h
  ssldisable: true
  force_path_style: true

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: blob-svc
  service_port: 80

connector:
  url: http://localhost:8054/integrations/doorman #TODO: CONFIGURE ANOTHER `url` PARAM
